//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetBadger.Language {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BudgetBadger.Language.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AccountBalanceLabel {
            get {
                return ResourceManager.GetString("AccountBalanceLabel", resourceCulture);
            }
        }
        
        public static string AccountDeleteInactiveError {
            get {
                return ResourceManager.GetString("AccountDeleteInactiveError", resourceCulture);
            }
        }
        
        public static string AccountEditPageTitle {
            get {
                return ResourceManager.GetString("AccountEditPageTitle", resourceCulture);
            }
        }
        
        public static string AccountNameLabel {
            get {
                return ResourceManager.GetString("AccountNameLabel", resourceCulture);
            }
        }
        
        public static string AccountNetWorthLabel {
            get {
                return ResourceManager.GetString("AccountNetWorthLabel", resourceCulture);
            }
        }
        
        public static string AccountNewPageTitle {
            get {
                return ResourceManager.GetString("AccountNewPageTitle", resourceCulture);
            }
        }
        
        public static string AccountNotesLabel {
            get {
                return ResourceManager.GetString("AccountNotesLabel", resourceCulture);
            }
        }
        
        public static string AccountPaymentLabel {
            get {
                return ResourceManager.GetString("AccountPaymentLabel", resourceCulture);
            }
        }
        
        public static string AccountPaymentNotNeededLabel {
            get {
                return ResourceManager.GetString("AccountPaymentNotNeededLabel", resourceCulture);
            }
        }
        
        public static string AccountPendingLabel {
            get {
                return ResourceManager.GetString("AccountPendingLabel", resourceCulture);
            }
        }
        
        public static string AccountPostedLabel {
            get {
                return ResourceManager.GetString("AccountPostedLabel", resourceCulture);
            }
        }
        
        public static string AccountReconcileAmountsDoNotMatchError {
            get {
                return ResourceManager.GetString("AccountReconcileAmountsDoNotMatchError", resourceCulture);
            }
        }
        
        public static string AccountReconcileDifferenceLabel {
            get {
                return ResourceManager.GetString("AccountReconcileDifferenceLabel", resourceCulture);
            }
        }
        
        public static string AccountReconcileEmptyTransactionsHelperTitle {
            get {
                return ResourceManager.GetString("AccountReconcileEmptyTransactionsHelperTitle", resourceCulture);
            }
        }
        
        public static string AccountReconcileStatementBalanceLabel {
            get {
                return ResourceManager.GetString("AccountReconcileStatementBalanceLabel", resourceCulture);
            }
        }
        
        public static string AccountReconcileStatementDateLabel {
            get {
                return ResourceManager.GetString("AccountReconcileStatementDateLabel", resourceCulture);
            }
        }
        
        public static string AccountReconcileStatementLabel {
            get {
                return ResourceManager.GetString("AccountReconcileStatementLabel", resourceCulture);
            }
        }
        
        public static string AccountSelectionPageTitle {
            get {
                return ResourceManager.GetString("AccountSelectionPageTitle", resourceCulture);
            }
        }
        
        public static string AccountsPageTitle {
            get {
                return ResourceManager.GetString("AccountsPageTitle", resourceCulture);
            }
        }
        
        public static string AccountTypeBudget {
            get {
                return ResourceManager.GetString("AccountTypeBudget", resourceCulture);
            }
        }
        
        public static string AccountTypeLabel {
            get {
                return ResourceManager.GetString("AccountTypeLabel", resourceCulture);
            }
        }
        
        public static string AccountTypeReporting {
            get {
                return ResourceManager.GetString("AccountTypeReporting", resourceCulture);
            }
        }
        
        public static string AccountUndoDeleteNotDeletedError {
            get {
                return ResourceManager.GetString("AccountUndoDeleteNotDeletedError", resourceCulture);
            }
        }
        
        public static string AccountValidBalanceError {
            get {
                return ResourceManager.GetString("AccountValidBalanceError", resourceCulture);
            }
        }
        
        public static string AccountValidDescriptionError {
            get {
                return ResourceManager.GetString("AccountValidDescriptionError", resourceCulture);
            }
        }
        
        public static string AddTransactionButton {
            get {
                return ResourceManager.GetString("AddTransactionButton", resourceCulture);
            }
        }
        
        public static string AlertAuthenticationUnsuccessful {
            get {
                return ResourceManager.GetString("AlertAuthenticationUnsuccessful", resourceCulture);
            }
        }
        
        public static string AlertBudgetBadgerPro {
            get {
                return ResourceManager.GetString("AlertBudgetBadgerPro", resourceCulture);
            }
        }
        
        public static string AlertCancel {
            get {
                return ResourceManager.GetString("AlertCancel", resourceCulture);
            }
        }
        
        public static string AlertDeleteUnsuccessful {
            get {
                return ResourceManager.GetString("AlertDeleteUnsuccessful", resourceCulture);
            }
        }
        
        public static string AlertGeneralError {
            get {
                return ResourceManager.GetString("AlertGeneralError", resourceCulture);
            }
        }
        
        public static string AlertMessageBudgetBadgerPro {
            get {
                return ResourceManager.GetString("AlertMessageBudgetBadgerPro", resourceCulture);
            }
        }
        
        public static string AlertMessageDropboxError {
            get {
                return ResourceManager.GetString("AlertMessageDropboxError", resourceCulture);
            }
        }
        
        public static string AlertNotPurchased {
            get {
                return ResourceManager.GetString("AlertNotPurchased", resourceCulture);
            }
        }
        
        public static string AlertOk {
            get {
                return ResourceManager.GetString("AlertOk", resourceCulture);
            }
        }
        
        public static string AlertPurchase {
            get {
                return ResourceManager.GetString("AlertPurchase", resourceCulture);
            }
        }
        
        public static string AlertPurchaseUnsuccessful {
            get {
                return ResourceManager.GetString("AlertPurchaseUnsuccessful", resourceCulture);
            }
        }
        
        public static string AlertQuickBudget {
            get {
                return ResourceManager.GetString("AlertQuickBudget", resourceCulture);
            }
        }
        
        public static string AlertQuickBudgetNotEnoughData {
            get {
                return ResourceManager.GetString("AlertQuickBudgetNotEnoughData", resourceCulture);
            }
        }
        
        public static string AlertReconcileUnsuccessful {
            get {
                return ResourceManager.GetString("AlertReconcileUnsuccessful", resourceCulture);
            }
        }
        
        public static string AlertRefreshUnsuccessful {
            get {
                return ResourceManager.GetString("AlertRefreshUnsuccessful", resourceCulture);
            }
        }
        
        public static string AlertRestorePurchaseUnsuccessful {
            get {
                return ResourceManager.GetString("AlertRestorePurchaseUnsuccessful", resourceCulture);
            }
        }
        
        public static string AlertSaveUnsuccessful {
            get {
                return ResourceManager.GetString("AlertSaveUnsuccessful", resourceCulture);
            }
        }
        
        public static string AlertSyncUnsuccessful {
            get {
                return ResourceManager.GetString("AlertSyncUnsuccessful", resourceCulture);
            }
        }
        
        public static string AlertUndoDeleteUnsuccessful {
            get {
                return ResourceManager.GetString("AlertUndoDeleteUnsuccessful", resourceCulture);
            }
        }
        
        public static string AutomaticLabel {
            get {
                return ResourceManager.GetString("AutomaticLabel", resourceCulture);
            }
        }
        
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        public static string BeginDateLabel {
            get {
                return ResourceManager.GetString("BeginDateLabel", resourceCulture);
            }
        }
        
        public static string BudgetBadger {
            get {
                return ResourceManager.GetString("BudgetBadger", resourceCulture);
            }
        }
        
        public static string BudgetBadgerProLabel {
            get {
                return ResourceManager.GetString("BudgetBadgerProLabel", resourceCulture);
            }
        }
        
        public static string BudgetBadgerProPurchaseLabel {
            get {
                return ResourceManager.GetString("BudgetBadgerProPurchaseLabel", resourceCulture);
            }
        }
        
        public static string BudgetBadgerProRestoreLabel {
            get {
                return ResourceManager.GetString("BudgetBadgerProRestoreLabel", resourceCulture);
            }
        }
        
        public static string BudgetBadgerProThanksLabel {
            get {
                return ResourceManager.GetString("BudgetBadgerProThanksLabel", resourceCulture);
            }
        }
        
        public static string BufferEnvelope {
            get {
                return ResourceManager.GetString("BufferEnvelope", resourceCulture);
            }
        }
        
        public static string BusyTextDeleting {
            get {
                return ResourceManager.GetString("BusyTextDeleting", resourceCulture);
            }
        }
        
        public static string BusyTextLoading {
            get {
                return ResourceManager.GetString("BusyTextLoading", resourceCulture);
            }
        }
        
        public static string BusyTextSaving {
            get {
                return ResourceManager.GetString("BusyTextSaving", resourceCulture);
            }
        }
        
        public static string BusyTextSyncing {
            get {
                return ResourceManager.GetString("BusyTextSyncing", resourceCulture);
            }
        }
        
        public static string BusyTextUndoingDelete {
            get {
                return ResourceManager.GetString("BusyTextUndoingDelete", resourceCulture);
            }
        }
        
        public static string CloudSyncLabel {
            get {
                return ResourceManager.GetString("CloudSyncLabel", resourceCulture);
            }
        }
        
        public static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        public static string DateTimeLabel {
            get {
                return ResourceManager.GetString("DateTimeLabel", resourceCulture);
            }
        }
        
        public static string DebtEnvelopeGroup {
            get {
                return ResourceManager.GetString("DebtEnvelopeGroup", resourceCulture);
            }
        }
        
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        public static string DeletedAccountsLabel {
            get {
                return ResourceManager.GetString("DeletedAccountsLabel", resourceCulture);
            }
        }
        
        public static string DeletedAccountsPageTitle {
            get {
                return ResourceManager.GetString("DeletedAccountsPageTitle", resourceCulture);
            }
        }
        
        public static string DeletedEnvelopeGroupsLabel {
            get {
                return ResourceManager.GetString("DeletedEnvelopeGroupsLabel", resourceCulture);
            }
        }
        
        public static string DeletedEnvelopeGroupsPageTitle {
            get {
                return ResourceManager.GetString("DeletedEnvelopeGroupsPageTitle", resourceCulture);
            }
        }
        
        public static string DeletedEnvelopesLabel {
            get {
                return ResourceManager.GetString("DeletedEnvelopesLabel", resourceCulture);
            }
        }
        
        public static string DeletedEnvelopesPageTitle {
            get {
                return ResourceManager.GetString("DeletedEnvelopesPageTitle", resourceCulture);
            }
        }
        
        public static string DeletedLabel {
            get {
                return ResourceManager.GetString("DeletedLabel", resourceCulture);
            }
        }
        
        public static string DeletedPayeesLabel {
            get {
                return ResourceManager.GetString("DeletedPayeesLabel", resourceCulture);
            }
        }
        
        public static string DeletedPayeesPageTitle {
            get {
                return ResourceManager.GetString("DeletedPayeesPageTitle", resourceCulture);
            }
        }
        
        public static string DropboxLabel {
            get {
                return ResourceManager.GetString("DropboxLabel", resourceCulture);
            }
        }
        
        public static string EmptyAccountHelperSubtitle {
            get {
                return ResourceManager.GetString("EmptyAccountHelperSubtitle", resourceCulture);
            }
        }
        
        public static string EmptyAccountHelperTitle {
            get {
                return ResourceManager.GetString("EmptyAccountHelperTitle", resourceCulture);
            }
        }
        
        public static string EmptyDeletedAccountsHelperTitle {
            get {
                return ResourceManager.GetString("EmptyDeletedAccountsHelperTitle", resourceCulture);
            }
        }
        
        public static string EmptyDeletedEnvelopeGroupsHelperTitle {
            get {
                return ResourceManager.GetString("EmptyDeletedEnvelopeGroupsHelperTitle", resourceCulture);
            }
        }
        
        public static string EmptyDeletedEnvelopesHelperTitle {
            get {
                return ResourceManager.GetString("EmptyDeletedEnvelopesHelperTitle", resourceCulture);
            }
        }
        
        public static string EmptyDeletedPayeesHelperTitle {
            get {
                return ResourceManager.GetString("EmptyDeletedPayeesHelperTitle", resourceCulture);
            }
        }
        
        public static string EmptyEnvelopeGroupHelperTitle {
            get {
                return ResourceManager.GetString("EmptyEnvelopeGroupHelperTitle", resourceCulture);
            }
        }
        
        public static string EmptyEnvelopeHelperSubtitle {
            get {
                return ResourceManager.GetString("EmptyEnvelopeHelperSubtitle", resourceCulture);
            }
        }
        
        public static string EmptyEnvelopeHelperTitle {
            get {
                return ResourceManager.GetString("EmptyEnvelopeHelperTitle", resourceCulture);
            }
        }
        
        public static string EmptyPayeeHelperTitle {
            get {
                return ResourceManager.GetString("EmptyPayeeHelperTitle", resourceCulture);
            }
        }
        
        public static string EmptyTransactionsHelperTitle {
            get {
                return ResourceManager.GetString("EmptyTransactionsHelperTitle", resourceCulture);
            }
        }
        
        public static string EndDateLabel {
            get {
                return ResourceManager.GetString("EndDateLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeActivityLabel {
            get {
                return ResourceManager.GetString("EnvelopeActivityLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeAmountLabel {
            get {
                return ResourceManager.GetString("EnvelopeAmountLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeDeleteDebtError {
            get {
                return ResourceManager.GetString("EnvelopeDeleteDebtError", resourceCulture);
            }
        }
        
        public static string EnvelopeDeleteIncomeError {
            get {
                return ResourceManager.GetString("EnvelopeDeleteIncomeError", resourceCulture);
            }
        }
        
        public static string EnvelopeDeleteRemainingBalanceError {
            get {
                return ResourceManager.GetString("EnvelopeDeleteRemainingBalanceError", resourceCulture);
            }
        }
        
        public static string EnvelopeEditPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeEditPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupEditPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeGroupEditPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupLabel {
            get {
                return ResourceManager.GetString("EnvelopeGroupLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupNameLabel {
            get {
                return ResourceManager.GetString("EnvelopeGroupNameLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupNewPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeGroupNewPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupNotesLabel {
            get {
                return ResourceManager.GetString("EnvelopeGroupNotesLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupSelectionPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeGroupSelectionPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupsPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeGroupsPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupValidDescriptionError {
            get {
                return ResourceManager.GetString("EnvelopeGroupValidDescriptionError", resourceCulture);
            }
        }
        
        public static string EnvelopeLabel {
            get {
                return ResourceManager.GetString("EnvelopeLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeNameLabel {
            get {
                return ResourceManager.GetString("EnvelopeNameLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeNewPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeNewPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeNotesLabel {
            get {
                return ResourceManager.GetString("EnvelopeNotesLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeOverspendingLabel {
            get {
                return ResourceManager.GetString("EnvelopeOverspendingLabel", resourceCulture);
            }
        }
        
        public static string EnvelopePastLabel {
            get {
                return ResourceManager.GetString("EnvelopePastLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeRemainingLabel {
            get {
                return ResourceManager.GetString("EnvelopeRemainingLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeSelectionPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeSelectionPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopesPageTitle {
            get {
                return ResourceManager.GetString("EnvelopesPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeSpendingReportPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeSpendingReportPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeTransferAmountLabel {
            get {
                return ResourceManager.GetString("EnvelopeTransferAmountLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeTransferButton {
            get {
                return ResourceManager.GetString("EnvelopeTransferButton", resourceCulture);
            }
        }
        
        public static string EnvelopeTransferDateLabel {
            get {
                return ResourceManager.GetString("EnvelopeTransferDateLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeTransferFromLabel {
            get {
                return ResourceManager.GetString("EnvelopeTransferFromLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeTransferPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeTransferPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeTransferToLabel {
            get {
                return ResourceManager.GetString("EnvelopeTransferToLabel", resourceCulture);
            }
        }
        
        public static string EnvelopeTrendsReportPageTitle {
            get {
                return ResourceManager.GetString("EnvelopeTrendsReportPageTitle", resourceCulture);
            }
        }
        
        public static string EnvelopeValidAmountError {
            get {
                return ResourceManager.GetString("EnvelopeValidAmountError", resourceCulture);
            }
        }
        
        public static string EnvelopeValidDescriptionError {
            get {
                return ResourceManager.GetString("EnvelopeValidDescriptionError", resourceCulture);
            }
        }
        
        public static string EnvelopeValidEnvelopeError {
            get {
                return ResourceManager.GetString("EnvelopeValidEnvelopeError", resourceCulture);
            }
        }
        
        public static string EnvelopeValidEnvelopeExistError {
            get {
                return ResourceManager.GetString("EnvelopeValidEnvelopeExistError", resourceCulture);
            }
        }
        
        public static string EnvelopeValidGroupError {
            get {
                return ResourceManager.GetString("EnvelopeValidGroupError", resourceCulture);
            }
        }
        
        public static string EnvelopeValidGroupValidError {
            get {
                return ResourceManager.GetString("EnvelopeValidGroupValidError", resourceCulture);
            }
        }
        
        public static string EnvelopeValidOverspendDebtError {
            get {
                return ResourceManager.GetString("EnvelopeValidOverspendDebtError", resourceCulture);
            }
        }
        
        public static string EnvelopeValidOverspendError {
            get {
                return ResourceManager.GetString("EnvelopeValidOverspendError", resourceCulture);
            }
        }
        
        public static string EnvelopeValidScheduleError {
            get {
                return ResourceManager.GetString("EnvelopeValidScheduleError", resourceCulture);
            }
        }
        
        public static string EnvelopeValidScheduleExistError {
            get {
                return ResourceManager.GetString("EnvelopeValidScheduleExistError", resourceCulture);
            }
        }
        
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        public static string GenericDebtEnvelope {
            get {
                return ResourceManager.GetString("GenericDebtEnvelope", resourceCulture);
            }
        }
        
        public static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }
        
        public static string IgnoredEnvelope {
            get {
                return ResourceManager.GetString("IgnoredEnvelope", resourceCulture);
            }
        }
        
        public static string IncomeEnvelope {
            get {
                return ResourceManager.GetString("IncomeEnvelope", resourceCulture);
            }
        }
        
        public static string IncomeEnvelopeGroup {
            get {
                return ResourceManager.GetString("IncomeEnvelopeGroup", resourceCulture);
            }
        }
        
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        public static string LastSyncedLabel {
            get {
                return ResourceManager.GetString("LastSyncedLabel", resourceCulture);
            }
        }
        
        public static string NetWorthReportPageTitle {
            get {
                return ResourceManager.GetString("NetWorthReportPageTitle", resourceCulture);
            }
        }
        
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        public static string OverspendingTypeAlwaysIgnore {
            get {
                return ResourceManager.GetString("OverspendingTypeAlwaysIgnore", resourceCulture);
            }
        }
        
        public static string OverspendingTypeDoNotIgnore {
            get {
                return ResourceManager.GetString("OverspendingTypeDoNotIgnore", resourceCulture);
            }
        }
        
        public static string OverspendingTypeIgnore {
            get {
                return ResourceManager.GetString("OverspendingTypeIgnore", resourceCulture);
            }
        }
        
        public static string PayeeDeleteAccountError {
            get {
                return ResourceManager.GetString("PayeeDeleteAccountError", resourceCulture);
            }
        }
        
        public static string PayeeDeleteFutureTransactionsError {
            get {
                return ResourceManager.GetString("PayeeDeleteFutureTransactionsError", resourceCulture);
            }
        }
        
        public static string PayeeDeleteInactiveError {
            get {
                return ResourceManager.GetString("PayeeDeleteInactiveError", resourceCulture);
            }
        }
        
        public static string PayeeDeleteStartingBalanceError {
            get {
                return ResourceManager.GetString("PayeeDeleteStartingBalanceError", resourceCulture);
            }
        }
        
        public static string PayeeEditPageTitle {
            get {
                return ResourceManager.GetString("PayeeEditPageTitle", resourceCulture);
            }
        }
        
        public static string PayeeLabel {
            get {
                return ResourceManager.GetString("PayeeLabel", resourceCulture);
            }
        }
        
        public static string PayeeNameLabel {
            get {
                return ResourceManager.GetString("PayeeNameLabel", resourceCulture);
            }
        }
        
        public static string PayeeNewPageTitle {
            get {
                return ResourceManager.GetString("PayeeNewPageTitle", resourceCulture);
            }
        }
        
        public static string PayeeNotesLabel {
            get {
                return ResourceManager.GetString("PayeeNotesLabel", resourceCulture);
            }
        }
        
        public static string PayeeSelectionPageTitle {
            get {
                return ResourceManager.GetString("PayeeSelectionPageTitle", resourceCulture);
            }
        }
        
        public static string PayeesPageTitle {
            get {
                return ResourceManager.GetString("PayeesPageTitle", resourceCulture);
            }
        }
        
        public static string PayeeSpendingReportPageTitle {
            get {
                return ResourceManager.GetString("PayeeSpendingReportPageTitle", resourceCulture);
            }
        }
        
        public static string PayeeTransferGroup {
            get {
                return ResourceManager.GetString("PayeeTransferGroup", resourceCulture);
            }
        }
        
        public static string PayeeTrendsReportPageTitle {
            get {
                return ResourceManager.GetString("PayeeTrendsReportPageTitle", resourceCulture);
            }
        }
        
        public static string PayeeValidDescriptionError {
            get {
                return ResourceManager.GetString("PayeeValidDescriptionError", resourceCulture);
            }
        }
        
        public static string PurchaseErrorAppStoreUnavailable {
            get {
                return ResourceManager.GetString("PurchaseErrorAppStoreUnavailable", resourceCulture);
            }
        }
        
        public static string PurchaseErrorBillingUnavailable {
            get {
                return ResourceManager.GetString("PurchaseErrorBillingUnavailable", resourceCulture);
            }
        }
        
        public static string PurchaseErrorConnection {
            get {
                return ResourceManager.GetString("PurchaseErrorConnection", resourceCulture);
            }
        }
        
        public static string PurchaseErrorGeneralError {
            get {
                return ResourceManager.GetString("PurchaseErrorGeneralError", resourceCulture);
            }
        }
        
        public static string PurchaseErrorInvalidProduct {
            get {
                return ResourceManager.GetString("PurchaseErrorInvalidProduct", resourceCulture);
            }
        }
        
        public static string PurchaseErrorItemUnavailable {
            get {
                return ResourceManager.GetString("PurchaseErrorItemUnavailable", resourceCulture);
            }
        }
        
        public static string PurchaseErrorNotPurchased {
            get {
                return ResourceManager.GetString("PurchaseErrorNotPurchased", resourceCulture);
            }
        }
        
        public static string PurchaseErrorPaymentInvalid {
            get {
                return ResourceManager.GetString("PurchaseErrorPaymentInvalid", resourceCulture);
            }
        }
        
        public static string PurchaseErrorPaymentNotAllowed {
            get {
                return ResourceManager.GetString("PurchaseErrorPaymentNotAllowed", resourceCulture);
            }
        }
        
        public static string PurchaseErrorProductRequestFailed {
            get {
                return ResourceManager.GetString("PurchaseErrorProductRequestFailed", resourceCulture);
            }
        }
        
        public static string PurchaseErrorRestoreFailed {
            get {
                return ResourceManager.GetString("PurchaseErrorRestoreFailed", resourceCulture);
            }
        }
        
        public static string PurchaseErrorServiceUnavailable {
            get {
                return ResourceManager.GetString("PurchaseErrorServiceUnavailable", resourceCulture);
            }
        }
        
        public static string PurchaseErrorUnknown {
            get {
                return ResourceManager.GetString("PurchaseErrorUnknown", resourceCulture);
            }
        }
        
        public static string PurchaseErrorUserCancelled {
            get {
                return ResourceManager.GetString("PurchaseErrorUserCancelled", resourceCulture);
            }
        }
        
        public static string PurchaseErrorVerifyFailed {
            get {
                return ResourceManager.GetString("PurchaseErrorVerifyFailed", resourceCulture);
            }
        }
        
        public static string QuickBudgetAvgPast3MonthsActivity {
            get {
                return ResourceManager.GetString("QuickBudgetAvgPast3MonthsActivity", resourceCulture);
            }
        }
        
        public static string QuickBudgetAvgPast3MonthsBudgeted {
            get {
                return ResourceManager.GetString("QuickBudgetAvgPast3MonthsBudgeted", resourceCulture);
            }
        }
        
        public static string QuickBudgetAvgPastYearActivity {
            get {
                return ResourceManager.GetString("QuickBudgetAvgPastYearActivity", resourceCulture);
            }
        }
        
        public static string QuickBudgetAvgPastYearBudgeted {
            get {
                return ResourceManager.GetString("QuickBudgetAvgPastYearBudgeted", resourceCulture);
            }
        }
        
        public static string QuickBudgetBalance {
            get {
                return ResourceManager.GetString("QuickBudgetBalance", resourceCulture);
            }
        }
        
        public static string QuickBudgetButton {
            get {
                return ResourceManager.GetString("QuickBudgetButton", resourceCulture);
            }
        }
        
        public static string QuickBudgetLastMonthActivity {
            get {
                return ResourceManager.GetString("QuickBudgetLastMonthActivity", resourceCulture);
            }
        }
        
        public static string QuickBudgetLastMonthBudgeted {
            get {
                return ResourceManager.GetString("QuickBudgetLastMonthBudgeted", resourceCulture);
            }
        }
        
        public static string ReconcileAccountButton {
            get {
                return ResourceManager.GetString("ReconcileAccountButton", resourceCulture);
            }
        }
        
        public static string ReconcileButton {
            get {
                return ResourceManager.GetString("ReconcileButton", resourceCulture);
            }
        }
        
        public static string ReportsPageTitle {
            get {
                return ResourceManager.GetString("ReportsPageTitle", resourceCulture);
            }
        }
        
        public static string ScheduleBudgetedLabel {
            get {
                return ResourceManager.GetString("ScheduleBudgetedLabel", resourceCulture);
            }
        }
        
        public static string ScheduleIncomeLabel {
            get {
                return ResourceManager.GetString("ScheduleIncomeLabel", resourceCulture);
            }
        }
        
        public static string ScheduleOverLabel {
            get {
                return ResourceManager.GetString("ScheduleOverLabel", resourceCulture);
            }
        }
        
        public static string SchedulePastLabel {
            get {
                return ResourceManager.GetString("SchedulePastLabel", resourceCulture);
            }
        }
        
        public static string ScheduleToBudgetLabel {
            get {
                return ResourceManager.GetString("ScheduleToBudgetLabel", resourceCulture);
            }
        }
        
        public static string ScheduleValidDescriptionError {
            get {
                return ResourceManager.GetString("ScheduleValidDescriptionError", resourceCulture);
            }
        }
        
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        public static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        public static string SplitTransactionButton {
            get {
                return ResourceManager.GetString("SplitTransactionButton", resourceCulture);
            }
        }
        
        public static string SplitTransactionPageTitle {
            get {
                return ResourceManager.GetString("SplitTransactionPageTitle", resourceCulture);
            }
        }
        
        public static string SplitTransactionRemainingLabel {
            get {
                return ResourceManager.GetString("SplitTransactionRemainingLabel", resourceCulture);
            }
        }
        
        public static string SplitTransactionRunningTotalLabel {
            get {
                return ResourceManager.GetString("SplitTransactionRunningTotalLabel", resourceCulture);
            }
        }
        
        public static string SplitTransactionTotalLabel {
            get {
                return ResourceManager.GetString("SplitTransactionTotalLabel", resourceCulture);
            }
        }
        
        public static string SplitTransactionValidTransactionsError {
            get {
                return ResourceManager.GetString("SplitTransactionValidTransactionsError", resourceCulture);
            }
        }
        
        public static string StartingBalancePayee {
            get {
                return ResourceManager.GetString("StartingBalancePayee", resourceCulture);
            }
        }
        
        public static string SyncButton {
            get {
                return ResourceManager.GetString("SyncButton", resourceCulture);
            }
        }
        
        public static string SyncDateTimeNever {
            get {
                return ResourceManager.GetString("SyncDateTimeNever", resourceCulture);
            }
        }
        
        public static string SystemEnvelopeGroup {
            get {
                return ResourceManager.GetString("SystemEnvelopeGroup", resourceCulture);
            }
        }
        
        public static string TransactactionInflowLabel {
            get {
                return ResourceManager.GetString("TransactactionInflowLabel", resourceCulture);
            }
        }
        
        public static string TransactactionOutflowLabel {
            get {
                return ResourceManager.GetString("TransactactionOutflowLabel", resourceCulture);
            }
        }
        
        public static string TransactionAccountLabel {
            get {
                return ResourceManager.GetString("TransactionAccountLabel", resourceCulture);
            }
        }
        
        public static string TransactionAmountLabel {
            get {
                return ResourceManager.GetString("TransactionAmountLabel", resourceCulture);
            }
        }
        
        public static string TransactionClearedLabel {
            get {
                return ResourceManager.GetString("TransactionClearedLabel", resourceCulture);
            }
        }
        
        public static string TransactionDeleteAccountDeletedError {
            get {
                return ResourceManager.GetString("TransactionDeleteAccountDeletedError", resourceCulture);
            }
        }
        
        public static string TransactionDeleteEnvelopeDeletedError {
            get {
                return ResourceManager.GetString("TransactionDeleteEnvelopeDeletedError", resourceCulture);
            }
        }
        
        public static string TransactionDeleteTransferDeletedPayeeError {
            get {
                return ResourceManager.GetString("TransactionDeleteTransferDeletedPayeeError", resourceCulture);
            }
        }
        
        public static string TransactionEditPageTitle {
            get {
                return ResourceManager.GetString("TransactionEditPageTitle", resourceCulture);
            }
        }
        
        public static string TransactionEnvelopeLabel {
            get {
                return ResourceManager.GetString("TransactionEnvelopeLabel", resourceCulture);
            }
        }
        
        public static string TransactionNewPageTitle {
            get {
                return ResourceManager.GetString("TransactionNewPageTitle", resourceCulture);
            }
        }
        
        public static string TransactionNotesLabel {
            get {
                return ResourceManager.GetString("TransactionNotesLabel", resourceCulture);
            }
        }
        
        public static string TransactionPayeeLabel {
            get {
                return ResourceManager.GetString("TransactionPayeeLabel", resourceCulture);
            }
        }
        
        public static string TransactionReconciledLabel {
            get {
                return ResourceManager.GetString("TransactionReconciledLabel", resourceCulture);
            }
        }
        
        public static string TransactionServiceDateLabel {
            get {
                return ResourceManager.GetString("TransactionServiceDateLabel", resourceCulture);
            }
        }
        
        public static string TransactionStatusLabel {
            get {
                return ResourceManager.GetString("TransactionStatusLabel", resourceCulture);
            }
        }
        
        public static string TransactionValidAccountDeletedAccountError {
            get {
                return ResourceManager.GetString("TransactionValidAccountDeletedAccountError", resourceCulture);
            }
        }
        
        public static string TransactionValidAccountDeletedError {
            get {
                return ResourceManager.GetString("TransactionValidAccountDeletedError", resourceCulture);
            }
        }
        
        public static string TransactionValidAccountError {
            get {
                return ResourceManager.GetString("TransactionValidAccountError", resourceCulture);
            }
        }
        
        public static string TransactionValidAccountExistError {
            get {
                return ResourceManager.GetString("TransactionValidAccountExistError", resourceCulture);
            }
        }
        
        public static string TransactionValidAmountDeletedAccountError {
            get {
                return ResourceManager.GetString("TransactionValidAmountDeletedAccountError", resourceCulture);
            }
        }
        
        public static string TransactionValidAmountDeletedEnvelopeError {
            get {
                return ResourceManager.GetString("TransactionValidAmountDeletedEnvelopeError", resourceCulture);
            }
        }
        
        public static string TransactionValidAmountDeletedPayeeError {
            get {
                return ResourceManager.GetString("TransactionValidAmountDeletedPayeeError", resourceCulture);
            }
        }
        
        public static string TransactionValidAmountError {
            get {
                return ResourceManager.GetString("TransactionValidAmountError", resourceCulture);
            }
        }
        
        public static string TransactionValidEnvelopeDeletedError {
            get {
                return ResourceManager.GetString("TransactionValidEnvelopeDeletedError", resourceCulture);
            }
        }
        
        public static string TransactionValidEnvelopeError {
            get {
                return ResourceManager.GetString("TransactionValidEnvelopeError", resourceCulture);
            }
        }
        
        public static string TransactionValidEnvelopeExistError {
            get {
                return ResourceManager.GetString("TransactionValidEnvelopeExistError", resourceCulture);
            }
        }
        
        public static string TransactionValidPayeeDeletedEnvelopeError {
            get {
                return ResourceManager.GetString("TransactionValidPayeeDeletedEnvelopeError", resourceCulture);
            }
        }
        
        public static string TransactionValidPayeeDeletedError {
            get {
                return ResourceManager.GetString("TransactionValidPayeeDeletedError", resourceCulture);
            }
        }
        
        public static string TransactionValidPayeeDeletedPayeeError {
            get {
                return ResourceManager.GetString("TransactionValidPayeeDeletedPayeeError", resourceCulture);
            }
        }
        
        public static string TransactionValidPayeeError {
            get {
                return ResourceManager.GetString("TransactionValidPayeeError", resourceCulture);
            }
        }
        
        public static string TransactionValidPayeeExistError {
            get {
                return ResourceManager.GetString("TransactionValidPayeeExistError", resourceCulture);
            }
        }
        
        public static string TransactionValidServiceDateDeletedAccountError {
            get {
                return ResourceManager.GetString("TransactionValidServiceDateDeletedAccountError", resourceCulture);
            }
        }
        
        public static string TransactionValidServiceDateDeletedEnvelopeError {
            get {
                return ResourceManager.GetString("TransactionValidServiceDateDeletedEnvelopeError", resourceCulture);
            }
        }
        
        public static string TransactionValidServiceDateDeletedPayeeError {
            get {
                return ResourceManager.GetString("TransactionValidServiceDateDeletedPayeeError", resourceCulture);
            }
        }
        
        public static string TransferValidFromerror {
            get {
                return ResourceManager.GetString("TransferValidFromerror", resourceCulture);
            }
        }
        
        public static string TransferValidToError {
            get {
                return ResourceManager.GetString("TransferValidToError", resourceCulture);
            }
        }
        
        public static string UndoDeleteButton {
            get {
                return ResourceManager.GetString("UndoDeleteButton", resourceCulture);
            }
        }
        
        public static string InternationalLabel {
            get {
                return ResourceManager.GetString("InternationalLabel", resourceCulture);
            }
        }
        
        public static string DetectLabel {
            get {
                return ResourceManager.GetString("DetectLabel", resourceCulture);
            }
        }
        
        public static string ManageGroupsButton {
            get {
                return ResourceManager.GetString("ManageGroupsButton", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupMonthlyBills {
            get {
                return ResourceManager.GetString("EnvelopeGroupMonthlyBills", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupEverydayExpenses {
            get {
                return ResourceManager.GetString("EnvelopeGroupEverydayExpenses", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupSavingsGoals {
            get {
                return ResourceManager.GetString("EnvelopeGroupSavingsGoals", resourceCulture);
            }
        }
        
        public static string AlertSuggestedEnvelopeGroups {
            get {
                return ResourceManager.GetString("AlertSuggestedEnvelopeGroups", resourceCulture);
            }
        }
        
        public static string AlertMessageSuggestedEnvelopeGroups {
            get {
                return ResourceManager.GetString("AlertMessageSuggestedEnvelopeGroups", resourceCulture);
            }
        }
        
        public static string EmptyReportsHelperTitle {
            get {
                return ResourceManager.GetString("EmptyReportsHelperTitle", resourceCulture);
            }
        }
        
        public static string AccountBalanceHint {
            get {
                return ResourceManager.GetString("AccountBalanceHint", resourceCulture);
            }
        }
        
        public static string AlertMessageDebtEnvelopes {
            get {
                return ResourceManager.GetString("AlertMessageDebtEnvelopes", resourceCulture);
            }
        }
        
        public static string AlertDebtEnvelopes {
            get {
                return ResourceManager.GetString("AlertDebtEnvelopes", resourceCulture);
            }
        }
        
        public static string AlertBudgetBadger {
            get {
                return ResourceManager.GetString("AlertBudgetBadger", resourceCulture);
            }
        }
        
        public static string AlertMessageEnjoyingBudgetBadger {
            get {
                return ResourceManager.GetString("AlertMessageEnjoyingBudgetBadger", resourceCulture);
            }
        }
        
        public static string AlertYes {
            get {
                return ResourceManager.GetString("AlertYes", resourceCulture);
            }
        }
        
        public static string AlertNotReally {
            get {
                return ResourceManager.GetString("AlertNotReally", resourceCulture);
            }
        }
        
        public static string AlertReview {
            get {
                return ResourceManager.GetString("AlertReview", resourceCulture);
            }
        }
        
        public static string AlertMessageReview {
            get {
                return ResourceManager.GetString("AlertMessageReview", resourceCulture);
            }
        }
        
        public static string AlertOkSure {
            get {
                return ResourceManager.GetString("AlertOkSure", resourceCulture);
            }
        }
        
        public static string AlertNoThanks {
            get {
                return ResourceManager.GetString("AlertNoThanks", resourceCulture);
            }
        }
        
        public static string AlertFeedback {
            get {
                return ResourceManager.GetString("AlertFeedback", resourceCulture);
            }
        }
        
        public static string AlertMessageFeedback {
            get {
                return ResourceManager.GetString("AlertMessageFeedback", resourceCulture);
            }
        }
        
        public static string PurchaseProButton {
            get {
                return ResourceManager.GetString("PurchaseProButton", resourceCulture);
            }
        }
        
        public static string RestoreProButton {
            get {
                return ResourceManager.GetString("RestoreProButton", resourceCulture);
            }
        }
        
        public static string UnlockCloudSyncLabel {
            get {
                return ResourceManager.GetString("UnlockCloudSyncLabel", resourceCulture);
            }
        }
        
        public static string UnlockReportsLabel {
            get {
                return ResourceManager.GetString("UnlockReportsLabel", resourceCulture);
            }
        }
        
        public static string BudgetValidAlreadyExists {
            get {
                return ResourceManager.GetString("BudgetValidAlreadyExists", resourceCulture);
            }
        }
        
        public static string EnvelopeDeleteNonZeroBudgetsError {
            get {
                return ResourceManager.GetString("EnvelopeDeleteNonZeroBudgetsError", resourceCulture);
            }
        }
        
        public static string EnvelopeDeleteSystemError {
            get {
                return ResourceManager.GetString("EnvelopeDeleteSystemError", resourceCulture);
            }
        }
        
        public static string EnvelopeDeleteActiveTransactionsError {
            get {
                return ResourceManager.GetString("EnvelopeDeleteActiveTransactionsError", resourceCulture);
            }
        }
        
        public static string EnvelopeDeleteNotHiddenError {
            get {
                return ResourceManager.GetString("EnvelopeDeleteNotHiddenError", resourceCulture);
            }
        }
        
        public static string EnvelopeHideInactiveError {
            get {
                return ResourceManager.GetString("EnvelopeHideInactiveError", resourceCulture);
            }
        }
        
        public static string EnvelopeHideSystemError {
            get {
                return ResourceManager.GetString("EnvelopeHideSystemError", resourceCulture);
            }
        }
        
        public static string EnvelopeUnhideNotHiddenError {
            get {
                return ResourceManager.GetString("EnvelopeUnhideNotHiddenError", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupDeleteNotHiddenError {
            get {
                return ResourceManager.GetString("EnvelopeGroupDeleteNotHiddenError", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupDeleteSystemError {
            get {
                return ResourceManager.GetString("EnvelopeGroupDeleteSystemError", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupDeleteActiveEnvelopesError {
            get {
                return ResourceManager.GetString("EnvelopeGroupDeleteActiveEnvelopesError", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupHideInactiveError {
            get {
                return ResourceManager.GetString("EnvelopeGroupHideInactiveError", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupHideSystemError {
            get {
                return ResourceManager.GetString("EnvelopeGroupHideSystemError", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupHideActiveEnvelopesError {
            get {
                return ResourceManager.GetString("EnvelopeGroupHideActiveEnvelopesError", resourceCulture);
            }
        }
        
        public static string EnvelopeGroupUnhideNotHiddenError {
            get {
                return ResourceManager.GetString("EnvelopeGroupUnhideNotHiddenError", resourceCulture);
            }
        }
        
        public static string AccountDeleteNotHiddenError {
            get {
                return ResourceManager.GetString("AccountDeleteNotHiddenError", resourceCulture);
            }
        }
        
        public static string AccountDeleteActiveTransactionsError {
            get {
                return ResourceManager.GetString("AccountDeleteActiveTransactionsError", resourceCulture);
            }
        }
        
        public static string AccountHideInactiveError {
            get {
                return ResourceManager.GetString("AccountHideInactiveError", resourceCulture);
            }
        }
        
        public static string AccountUnhideNotHiddenError {
            get {
                return ResourceManager.GetString("AccountUnhideNotHiddenError", resourceCulture);
            }
        }
        
        public static string PayeeDeleteNotHiddenError {
            get {
                return ResourceManager.GetString("PayeeDeleteNotHiddenError", resourceCulture);
            }
        }
        
        public static string PayeeDeleteSystemError {
            get {
                return ResourceManager.GetString("PayeeDeleteSystemError", resourceCulture);
            }
        }
        
        public static string PayeeDeleteActiveTransactionsError {
            get {
                return ResourceManager.GetString("PayeeDeleteActiveTransactionsError", resourceCulture);
            }
        }
        
        public static string PayeeHideInactiveError {
            get {
                return ResourceManager.GetString("PayeeHideInactiveError", resourceCulture);
            }
        }
        
        public static string PayeeHideSystemError {
            get {
                return ResourceManager.GetString("PayeeHideSystemError", resourceCulture);
            }
        }
        
        public static string PayeeUnhideNotHiddenError {
            get {
                return ResourceManager.GetString("PayeeUnhideNotHiddenError", resourceCulture);
            }
        }
        
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        public static string HiddenAccountsPageTitle {
            get {
                return ResourceManager.GetString("HiddenAccountsPageTitle", resourceCulture);
            }
        }
        
        public static string EmptyHiddenAccountsHelperTitle {
            get {
                return ResourceManager.GetString("EmptyHiddenAccountsHelperTitle", resourceCulture);
            }
        }
        
        public static string HiddenPayeesPageTitle {
            get {
                return ResourceManager.GetString("HiddenPayeesPageTitle", resourceCulture);
            }
        }
        
        public static string EmptyHiddenPayeesHelperTitle {
            get {
                return ResourceManager.GetString("EmptyHiddenPayeesHelperTitle", resourceCulture);
            }
        }
        
        public static string HiddenEnvelopeGroupsPageTitle {
            get {
                return ResourceManager.GetString("HiddenEnvelopeGroupsPageTitle", resourceCulture);
            }
        }
        
        public static string EmptyHiddenEnvelopeGroupsHelperTitle {
            get {
                return ResourceManager.GetString("EmptyHiddenEnvelopeGroupsHelperTitle", resourceCulture);
            }
        }
        
        public static string HiddenEnvelopesPageTitle {
            get {
                return ResourceManager.GetString("HiddenEnvelopesPageTitle", resourceCulture);
            }
        }
        
        public static string EmptyHiddenEnvelopesHelperTitle {
            get {
                return ResourceManager.GetString("EmptyHiddenEnvelopesHelperTitle", resourceCulture);
            }
        }
        
        public static string AlertHideUnsuccessful {
            get {
                return ResourceManager.GetString("AlertHideUnsuccessful", resourceCulture);
            }
        }
        
        public static string BusyTextHiding {
            get {
                return ResourceManager.GetString("BusyTextHiding", resourceCulture);
            }
        }
        
        public static string BusyTextUnhiding {
            get {
                return ResourceManager.GetString("BusyTextUnhiding", resourceCulture);
            }
        }
        
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        public static string HideButton {
            get {
                return ResourceManager.GetString("HideButton", resourceCulture);
            }
        }
        
        public static string UnhideButton {
            get {
                return ResourceManager.GetString("UnhideButton", resourceCulture);
            }
        }
        
        public static string AlertUnhideUnsuccessful {
            get {
                return ResourceManager.GetString("AlertUnhideUnsuccessful", resourceCulture);
            }
        }
        
        public static string AlertConfirmation {
            get {
                return ResourceManager.GetString("AlertConfirmation", resourceCulture);
            }
        }
        
        public static string AlertConfirmDelete {
            get {
                return ResourceManager.GetString("AlertConfirmDelete", resourceCulture);
            }
        }
    }
}
