trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
- group: budgetbadger_variables

steps:
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(mono_version)
  displayName: 'Select the Xamarin SDK version'
  enabled: true
  
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'mac_distribution_cert.p12'
    certPwd: '$(mac_distribution_cert_password)'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Budget_Badger_Mac_AppStore.provisionprofile'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.BinariesDirectory)'
    ArtifactName: 'BudgetBadger.macOS'
    publishLocation: 'Container'
