trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
- group: budgetbadger_variables

steps:
- task: DownloadSecureFile@1
  name: appsettings
  inputs:
    secureFile: 'appsettings.json'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(appsettings.secureFilePath)'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/BudgetBadger.Forms'

- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(mono_version)
  displayName: 'Select the Xamarin SDK version'
  enabled: true
  
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid.csproj'
    outputDirectory: '$(Build.BinariesDirectory)'
    configuration: 'Release'
    jdkOption: 'JDKVersion'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)'
    Contents: '*.apk'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'BudgetBadger.Android'
    publishLocation: 'pipeline'