name: Build BudgetBadger.Android

on: [push]

jobs:
  Android:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v3
    - name: Build
      run: msbuild ./BudgetBadger.Android/BudgetBadger.Android.csproj /t:restore /t:PackageForAndroid /p:Configuration=Debug
