name: test

on: [push, pull_request, workflow_dispatch]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.202'

      - name: Print environment
        run: |
             nuget help | grep Version
             msbuild -version
             dotnet --info
             echo "GitHub ref: $GITHUB_REF"
             echo "GitHub event: $GITHUB_EVENT"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore
        run: dotnet restore ./tests/BudgetBadger.UnitTests/BudgetBadger.UnitTests.csproj

      - name: Build
        run: dotnet build ./tests/BudgetBadger.UnitTests/BudgetBadger.UnitTests.csproj

      - name: Test
        run: dotnet test ./tests/BudgetBadger.UnitTests/BudgetBadger.UnitTests.csproj --verbosity normal

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.202'

      - name: Print environment
        run: |
             nuget help | grep Version
             msbuild -version
             dotnet --info
             echo "GitHub ref: $GITHUB_REF"
             echo "GitHub event: $GITHUB_EVENT"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore
        run: dotnet restore ./tests/BudgetBadger.IntegrationTests/BudgetBadger.IntegrationTests.csproj

      - name: Build
        run: dotnet build ./tests/BudgetBadger.IntegrationTests/BudgetBadger.IntegrationTests.csproj

      - name: Test
        run: dotnet test ./tests/BudgetBadger.IntegrationTests/BudgetBadger.IntegrationTests.csproj --verbosity normal
